services:
  scraper:
    build: .
    command: bundle exec rake scrape:all
    env_file:
      - path: .env
        required: false
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle

volumes:
  bundle_cache:
